---
title: "CentauriumChrom"
author: "Marcial Escudero"
date: "8/9/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
#library("devtools")
#devtools::install_github("roszenil/chromploid")
library("chromploid")
library("geiger")
library("nloptr")

mydata <- read.csv("Centaurium input_AncestralAreas.csv")
mydata
mydata <- mydata[match(mydata[,1], mytree$tip.label),]

mydata1 <- mydata[,2:3]
rownames(mydata1) <- mydata[,1]
mydata1
mysample <- bichrom_dataset(mydata1, size = 28, state.0 = "0", state.1 = "1")
mytree <- read.tree("Centaurium.tree")
mytree$tip.label

x.0 <- log(c(0.12, 0.001, 0.25, 0.002, 0.036, 0.006, 0.04, 0.02,
1.792317852, 1.57e-14))
# value where the optimization algorithm is going to start. A
# vector of 10 values for the parameters in log scale

model.args <- list(size = 28)
optimization.bichrom <- bichrom_optim(phy.tree = mytree, tip.values = mysample,
model = "bichrom", model.args = model.args, starting.val = x.0,
root.dist = NULL)

print(optimization.bichrom)


x.0 <- log(c(0.12, 0.001, 0.25, 0.002, 0.01, 0.04, 0.02, 1.792317852,
1.57e-14))
# Value where the optimization algorithm is going to start. A
# vector of 9 values for the parameters in log scale. The
# value of the hypothesis here is rho=0.010

model.args = list(size = 28, equal.param = c("rh0", "rho1"),
location.par = 5)
# Q.ARGS is a list that has all the arguments included in
# Q_reducedbichrom that are not the parameters size= maximum
# number of haploid chromosome numbers to consider in your
# sample, equal.params=which parameters are equal based on
# the hypothesis H0, location.par is the position in the
# vector where rho value appears

optimization.reducedbichrom <- bichrom_optim(phy.tree = mytree,
tip.values = mysample, model = "reducedbichrom", model.args = model.args,
starting.val = x.0, root.dist = NULL)

print(optimization.reducedbichrom)

#Maybe it is demipolyploidy
x.0 <- log(c(0.12, 0.001, 0.25, 0.002, 0.036, 0.006, 0.04, 0.02,
1.792317852))
model.args = list(size = 28, equal.param = c("epsilon0", "epsion1"),
location.par = 9)
optimization.reducedbichrom2 <- bichrom_optim(phy.tree = mytree,
tip.values = mysample, model = "reducedbichrom", model.args = model.args,
starting.val = x.0, root.dist = NULL)

rownames(optimization.reducedbichrom2) <- c("lambda0", "lambda1", "mu0", "mu1", "rho0", "rho1", "q01", "q10", "epsilon", "nloglike", "convergencestatus")
print(optimization.reducedbichrom2)


neglog.red <- optimization.reducedbichrom$results[10]
neglog.full <- optimization.bichrom$results[11]
alpha <- 0.05
D = 2 * (neglog.red - neglog.full)
p.value <- pchisq(D, lower.tail = FALSE, df = 1)
if (p.value > 0.05) {
reject <- 0
} else {
reject <- 1
}

```

Plotting some results from ChromEvol 1.0
```{r}
library(ape)
myChromEvol <- read.ce("/home/amesclir/Downloads/centauriumDEF/OUT/CONST_RATE_DEMI_EST")
plot.anc(myChromEvol)

```


Plotting the ChromoSSE results

```{r}
#library(devtools)
#devtools::install_github("cmt2/RevGadgets", force = T)

library(RevGadgets)
library(coda)
library(ggplot2)
library(ggtree)
library(grid)
library(gridExtra)

file <- "ChromEvol_clado_final.tree"
labs <- c("10" = "10", "11" = "11", "14" = "14", "15" = "15", "18" = "18", "19" = "19", "20" = "20", "21" = "21", "27" = "27", "28" = "28", "3" = "3", "4" = "4", "5" = "5", "6" = "6", "7" = "7", "8" = "8", "9" = "9")

dec_example <- processAncStates(file, labs)

plotAncStatesPie(dec_example, cladogenetic = T, tip_labels_offset = 0.2)

# You can see the states sampled in the analysis in the
# dec_example@state_labels vector. This may be different 
# from the `labs` vector you provided above if not all 
# possible states are included in the annotated tree.
dec_example@state_labels

# We are going to generate colors for these states using
# a color palette, but you could also specify a color per
# state manually. 

# Get the length of the dec_example$state_labels vector
# to know how many colors you need. 
ncol <- length(dec_example@state_labels)

# We use colorRampPalette() to generate a function that will
# expand the RevGadgets color palette (colFun) to the necessary
# number of colors, but you can use any colors you like as long 
# as each state_label has a color. 
colors <- colorRampPalette(colFun(12))(ncol)

# Name the color vector with your state labels and then order 
# it in the order you'd like the ranges to appear in your legend.
# Otherwise, they will appear alphabetically. 
names(colors) <- dec_example@state_labels
colors
colors <- colors[c(10,11,14,15,
                  18,19,20,21,27,28,
                  3,4,5,6,7,
                  8,9)]

# Plot the results with pies at nodes
pie <- plotAncStatesPie(t = dec_example,
                        # Include cladogenetic events
                        cladogenetic = TRUE, 
                        # Add text labels to the tip pie symbols
                        tip_labels_states = TRUE,
                        # Offset those text labels slightly
                        tip_labels_states_offset = .05,
                        # Pass in your named and ordered color vector
                        pie_colors = colors, 
                        # Offset the tip labels to make room for tip pies
                        tip_labels_offset = .2, 
                        # Move tip pies right slightly 
                        tip_pie_nudge_x = .07,
                        # Change the size of node and tip pies  
                        tip_pie_size = 0.8,
                        node_pie_size = 1.5) +
  # Move the legend 
  theme(legend.position = c(0.1, 0.75))

map <- plotAncStatesMAP(t = dec_example, 
                        # Include cladogenetic events
                        cladogenetic = T,
                        # Pass in the same color vector
                        node_color = colors,
                        # adjust tip labels 
                        tip_labels_offset = 0.1,
                        # increase tip states symbol size
                        tip_states_size = 3) +
  # adjust legend position and remove color guide
  theme(legend.position = c(0.2, 0.87)) + 
  guides(color = FALSE)

```

